export const dataList = [
  {
    type: "restaurant",
    data: {
      id: "41801",
      name: "Behrouz Biryani",
      cloudinaryImageId: "kdvh55bvfvzodn00qnn0",
      cuisines: [
        "Biryani",
        "Mughlai",
        "Lucknowi",
        "Hyderabadi",
        "Kebabs",
        "North Indian",
        "Desserts",
        "Beverages",
      ],
      costForTwo: 50000,
      deliveryTime: 28,
      avgRating: "4.3",
      totalRatings: 1000,
    },
  },
  {
    type: "restaurant",
    data: {
      id: "631826",
      name: "Pizza Hut",
      cloudinaryImageId: "2b4f62d606d1b2bfba9ba9e5386fabb7",
      cuisines: ["Pizzas"],
      costForTwo: 35000,
      deliveryTime: 22,
      avgRating: "3.7",
      totalRatings: 100,
    },
  },
  {
    data: {
      id: "115345",
      name: "Kakke Da Paratha",
      cloudinaryImageId: "xphkjf4xcwry0qe9exls",
      cuisines: ["North Indian", "Punjabi", "Thalis"],
      costForTwo: 20000,
      deliveryTime: 21,
      avgRating: "4.3",
      totalRatings: 5000,
    },
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "41802",
      name: "Oven Story Pizza",
      uuid: "c9202c35-4018-4ee9-8059-f0442ce48d80",
      city: "6",
      area: "Hinjawadi",
      totalRatingsString: "1000+ ratings",
      cloudinaryImageId: "ab979bffbd658e74de650a15ca0092a3",
      cuisines: ["Pizzas", "Pastas", "Italian", "Desserts", "Beverages"],
      tags: [],
      costForTwo: 40000,
      costForTwoString: "₹400 FOR TWO",
      deliveryTime: 35,
      avgRating: "3.9",
      totalRatings: 1000,
      new: false,
    },
  },
  {
    type: "restaurant",
    data: {
      id: "699055",
      name: "Chef's Corner",
      cloudinaryImageId: "af9e03f9426b41ecb73e6d0e523a335d",
      cuisines: ["Indian", "Fast Food", "Snacks"],
      costForTwo: 20000,
      deliveryTime: 22,
      avgRating: "--",
      totalRatings: 0,
    },
  },
  {
    type: "restaurant",
    data: {
      id: "580392",
      name: "Cheesemates pizza",
      cloudinaryImageId: "cihhedybbjndmgtk9hzu",
      cuisines: ["Pizzas", "Pastas", "Snacks"],
      costForTwo: 20000,
      deliveryTime: 21,
      avgRating: "--",
      totalRatings: 0,
    },
  },
  {
    type: "restaurant",
    data: {
      id: "446872",
      name: "Pizza Bites",
      cloudinaryImageId: "be87ef87d60b0e6baa2a24c080065c30",
      cuisines: ["Pizzas", "Italian", "Pastas", "Desserts"],
      costForTwo: 30000,
      deliveryTime: 34,
      avgRating: "3.4",
      totalRatings: 100,
    },
  },
  {
    type: "restaurant",
    data: {
      id: "459856",
      name: "Chole Bhature And Parathas",
      cloudinaryImageId: "z4ezgj9vih7au4prfibb",
      cuisines: ["Indian", "Chinese"],
      costForTwo: 20000,
      deliveryTime: 36,
      avgRating: "3.0",
      totalRatings: 100,
    },
  },
  {
    type: "restaurant",
    data: {
      id: "658746",
      name: "Spicy Island",
      cloudinaryImageId: "74b379136cb93be172d79af6037de95c",
      cuisines: ["Chinese"],
      costForTwo: 20000,
      deliveryTime: 20,
      avgRating: "3.7",
      totalRatings: 20,
    },
  },
  {
    type: "restaurant",
    data: {
      id: "571833",
      name: "CAKE XPRESS",
      cloudinaryImageId: "nqxx0yyineg4q4d8b54n",
      cuisines: ["Bakery", "Snacks"],
      costForTwo: 40000,
      deliveryTime: 26,
      avgRating: "--",
      totalRatings: 0,
    },
  },
  {
    type: "restaurant",
    data: {
      id: "493999",
      name: "MARWADI TADKA WALA",
      cloudinaryImageId: "uvjdiheyz66attf8zsmt",
      cuisines: ["Snacks"],
      costForTwo: 30000,
      deliveryTime: 30,
      avgRating: "3.0",
      totalRatings: 20,
    },
  },
  {
    type: "restaurant",
    data: {
      id: "459350",
      name: "Marwadi Chaat Tiffin Services",
      cloudinaryImageId: "mincavli2bxi3bjirdu4",
      cuisines: ["Indian", "Thalis"],
      costForTwo: 30000,
      deliveryTime: 34,
      avgRating: "3.4",
      totalRatings: 50,
    },
  },
  {
    type: "restaurant",
    data: {
      id: "632189",
      name: "New Hongkong Chinese & Food\t",
      cloudinaryImageId: "sv1kepmaybepesp0mpb8",
      cuisines: ["Chinese"],
      costForTwo: 30000,
      deliveryTime: 35,
      avgRating: "--",
      totalRatings: 0,
    },
  },
  {
    type: "restaurant",
    data: {
      id: "494002",
      name: "GHAR WALA KHANA",
      cloudinaryImageId: "tmkm4puwa3lpoi6fhsds",
      cuisines: ["Thalis"],
      costForTwo: 30000,
      deliveryTime: 28,
      avgRating: "2.8",
      totalRatings: 50,
    },
  },
  {
    type: "restaurant",
    data: {
      id: "494066",
      name: "PUNJAB TIME",
      cloudinaryImageId: "y5yfvazvmh3skyx7pso2",
      cuisines: ["North Indian", "Indian"],
      costForTwo: 30000,
      deliveryTime: 22,
      avgRating: "2.9",
      totalRatings: 50,
    },
  },
];
